### ISSUE TITLE
UnicodeEncodeError while parsing logs

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-stats#38]
```python
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_stats/management/commands/logparser.py", line 589, in handle
    p.process()
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_stats/management/commands/logparser.py", line 555, in process
    self._parse_line(line)
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_stats/management/commands/logparser.py", line 546, in _parse_line
    "[parser] no log handler for \"{}\": {}".format(prog, log))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 109: ordinal not in range(128)
```

**Comment by jaesivsm** [comment]
I think it'd be solved by #43
