### ISSUE TITLE
Stats graph not showing received mail

### ISSUE THREAD

**Issue by SteJay** [modoboa/modoboa-stats#42]
After a lot of messing about, I've finally gotten everything set up just the way I need it - Thanks for a great project; Modoboa seems to be the best oss mail server front end around!

Strangely, however, my mail traffic graph doesn't show received e-mail, only outgoing e-mail. I've read in a few places that I need to run "manage.py logparser" in a cron job (no cron jobs were set up by the installer), but I have tried running this: 

sudo -u modoboa /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py logparser

but the received mail stats still do not show up on the graph. I noticed there was also an "update_statistics" option, but if I try to run that I get this:
 
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_stats/management/commands/update_statistics.py", line 84, in handle
    self.update_account_creation_stats(options["rebuild"])
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_stats/management/commands/update_statistics.py", line 79, in update_account_creation_stats
    rrdtool.update(str(db_path), *data)
rrdtool.OperationalError: /srv/modoboa/rrdfiles/new_accounts.rrd: illegal attempt to update using time 1527127200 when last update time is 1527127200 (minimum one second step)

I'm not really sure where to look next - I notice others had problems with the graphs themselves, but the graphs are showing fine for me - I'm just not seeing anything except outgoing emails - the "Accounts" graphs also seem to be fine. Some more info that may be pertinent:

* I have rrdtool installed
* I have letsencrypt running and auto-renewing
* I am on Ubuntu 16.04 Server - a fresh install
* I installed using the installer (not a manual install)
* No crontab has been written (but I have included my own line to renew letsencrypt certs) - not sure if this indicates misconfiguration or not
* Mail in and out seems to be functioning fine
* The only other thing I've installed is roundcube, which is working perfectly

I'd appreciate any help or points in the right direction you can offer!

Thanks in advance -- Stephen

**Comment by SteJay** [comment]
My bad - they just appeared
