### ISSUE TITLE
rrdtool.OperationalError: new_accounts.rrd: illegal attempt to update using time  (minimum one second step)

### ISSUE THREAD

**Issue by jaesivsm** [modoboa/modoboa-stats#44]
# Impacted versions

 * modoboa==1.10.5
 * modoboa-stats==1.4.0
 * installer used: yes but not for upgrade
 * Webserver: Nginx (irrelevant)

# Steps to reproduce

```
root@server# $PYTHON $INSTANCE/manage.py update_statistics
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_stats/management/commands/update_statistics.py", line 84, in handle
    self.update_account_creation_stats(options["rebuild"])
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_stats/management/commands/update_statistics.py", line 79, in update_account_creation_stats
    rrdtool.update(str(db_path), *data)
rrdtool.OperationalError: /srv/modoboa/rrdfiles/new_accounts.rrd: illegal attempt to update using time 1528812000 when last update time is 1528812000 (minimum one second step)
```

**Comment by BioSs54** [comment]
Have same problem. Have you solved  it ??

**Comment by tonioo** [comment]
Looks like the script tries to record two samples for the same timestamp... Do you have this error every time you run the script? If you run it manually, make sure to respect the defined interval between 2 samples (5 minutes if I remember well)

**Comment by BioSs54** [comment]
You right tonioo. 
But I still have an error that comes up often : 
rrdtool.OperationalError: opening '/srv/modoboa/rrdfiles/new_accounts.rrd': Permission denied

ll /srv/modoboa/rrdfiles/new_accounts.rrd
-rw-r--r-- 1 root root 2448 juil. 12 11:00 /srv/modoboa/rrdfiles/new_accounts.rrd

Root is a good owner ?

**Comment by cremesk** [comment]
Same here.
